Added llvm to configure, disabled by default, also will not run if llvm is not here
Made a `make-configure' script that automates running autoconf and what
clean_ac.ss used to do; removed clean_ac.

svn: r271

diff --git a/src/mzscheme/make-configure b/src/mzscheme/make-configure
--- a/src/mzscheme/make-configure
+++ b/src/mzscheme/make-configure
@@ -1,3 +1,17 @@
+#!/bin/sh
+#|
+cd "`dirname \"$0\"`"
+src="configure.ac"
+tgt="../configure"
+if [ ! -e "$src" ]; then echo "abort: did not find $src"; exit 1; fi
+echo "Creating $tgt from $src"
+if [ -e "$tgt" ]; then
+  echo -n "overwriting $tgt, Ctrl-C to abort, enter to continue "; read R;
+fi
+autoconf "$src" | mzscheme -r "$0" > "$tgt"
+chmod +x "$tgt"
+exit 0
+|#
 
 ;; When autoconf produces `configure', it includes many
 ;;  options that do not apply to PLT software. We want to
