configure: add `--enable-sofind=<conv>` and `/sofind <conv>`
Generalize `--enable-natipkg` and `--enable-nonatipkg` to let
configuration name any shared-object convention. Add a similar
`/sofind` option to `winfig.bat`, so that a Windows build can be
configured to not install Racket packages for native libraries (which
makes sense if native libraries are installed in a different way).

diff --git a/racket/src/bc/configure b/racket/src/bc/configure
--- a/racket/src/bc/configure
+++ b/racket/src/bc/configure
@@ -1518,8 +1518,9 @@ Optional Features:
   --enable-docs           build docs on install (enabled by default)
   --enable-usersetup      setup user-specific files on install
   --enable-portable       prefer portable to host-specific
-  --enable-natipkg        add "-natipkg" to library subpath
-  --enable-nonatipkg      add "-nonatipkg" to library subpath
+  --enable-natipkg        use "natipkg" as shared-object convention
+  --enable-nonatipkg      use "nonatipkg" as shared-object convention
+  --enable-sofind=<conv>  use "<conv>" as shared-object convention
   --enable-shared         create shared libraries (ok, but not recommended)
   --enable-dynlib         same as --enable-shared
   --enable-lt=<prog>      use <prog> instead of libtool; disable to use bundled
@@ -2782,6 +2783,11 @@ if test "${enable_natipkg+set}" = set; then :
   enableval=$enable_natipkg;
 fi
 
+# Check whether --enable-natipkg was given.
+if test "${enable_natipkg+set}" = set; then :
+  enableval=$enable_natipkg;
+fi
+
 
 
 # Check whether --enable-shared was given.
@@ -3439,8 +3445,11 @@ show_explicitly_disabled "${enable_docs}" "Documentation build"
 show_explicitly_enabled "${enable_usersetup}" "User-specific setup on install"
 show_explicitly_enabled "${enable_portable}" "portable"
 
-show_explicitly_enabled "${enable_natipkg}" "Adding \"-natipkg\" suffix to library subpath"
-show_explicitly_enabled "${enable_nonatipkg}" "Adding \"-nonatipkg\" suffix to library subpath"
+show_explicitly_enabled "${enable_natipkg}" "Adding \"natipkg\" as shared-object convention and library subpath"
+show_explicitly_enabled "${enable_nonatipkg}" "Adding \"nonatipkg\" as shared-object convention and library subpath"
+if test "${enable_sofind}" != "" ; then
+   echo "=== Setting shared-object convention and library-subpath suffix to ${enable_sofind}"
+fi
 
 
 show_explicitly_enabled "${enable_xonx}" "Unix style"
@@ -7411,6 +7420,41 @@ fi
 
 ############## natipkg ################
 
+if test "${enable_natipkg}" = "no" ; then
+  if "${enable_nonatipkg}" = "" ; then
+    if "${enable_sofind}" = "" ; then
+       enable_nonatipkg=yes
+    fi
+  fi
+fi
+
+if test "${enable_nonatipkg}" = "yes" ; then
+  if test "${enable_natipkg}" = "yes" ; then
+     echo 'cannot specify both `--enable-natipkg` and `--enable-nonatipkg`'
+     exit 1
+  fi
+elif test "${enable_nonatipkg}" = "no" ; then
+  if "${enable_nonatipkg}" = "no" ; then
+    if "${enable_sofind}" = "" ; then
+       echo 'cannot specify both `--disable-natipkg` and `--disable-nonatipkg`'
+       echo 'without `--enable-sofind=<sofind>`'
+       exit 1
+    fi
+  fi
+fi
+
+if test "${enable_sofind}" != "" ; then
+  if test "${enable_natipkg}" = "yes" ; then
+     echo 'cannot specify both `--enable-natipkg` and `--enable-sofind`'
+     exit 1
+  fi
+  if test "${enable_nonatipkg}" = "yes" ; then
+     echo 'cannot specify both `--enable-nonatipkg` and `--enable-sofind`'
+     exit 1
+  fi
+fi
+
+
 if test "${enable_natipkg}" = "yes" ; then
 
 $as_echo "#define SPLS_SUFFIX \"-natipkg\"" >>confdefs.h
@@ -7418,14 +7462,17 @@ $as_echo "#define SPLS_SUFFIX \"-natipkg\"" >>confdefs.h
   dist_install_missing_pkgs=yes
 fi
 if test "${enable_nonatipkg}" = "yes" ; then
-  if test "${enable_natipkg}" = "yes" ; then
-     echo 'cannot specify both `--enable-natipkg` and `--enable-nonatipkg`'
-     exit 1
-  fi
 
 $as_echo "#define SPLS_SUFFIX \"-nonatipkg\"" >>confdefs.h
 
   dist_install_missing_pkgs=no
+fi
+if test "${enable_sofind}" != "" ; then
+
+cat >>confdefs.h <<_ACEOF
+#define SPLS_SUFFIX "-${enable_sofind}"
+_ACEOF
+
 fi
 
 ############## Racket for Racket ################
diff --git a/racket/src/cs/c/configure b/racket/src/cs/c/configure
--- a/racket/src/cs/c/configure
+++ b/racket/src/cs/c/configure
@@ -1486,8 +1486,9 @@ Optional Features:
   --enable-pbchunk        enable C chunks for pb boot (enabled by default)
   --enable-check          enable extra safety checks for testing
   --enable-portable       prefer portable to host-specific
-  --enable-natipkg        add "-natipkg" to library subpath
-  --enable-nonatipkg      add "-nonatipkg" to library subpath
+  --enable-natipkg        use "natipkg" as shared-object convention
+  --enable-nonatipkg      use "nonatipkg" as shared-object convention
+  --enable-sofind=<conv>  use "<conv>" as shared-object convention
   --enable-sdk=<path>     use Mac OS 10.4 SDK directory
   --enable-sdk5=<path>    use Mac OS 10.5 SDK directory
   --enable-sdk6=<path>    use Mac OS 10.6 SDK directory
@@ -2703,6 +2704,11 @@ if test "${enable_natipkg+set}" = set; then :
   enableval=$enable_natipkg;
 fi
 
+# Check whether --enable-natipkg was given.
+if test "${enable_natipkg+set}" = set; then :
+  enableval=$enable_natipkg;
+fi
+
 
 # Check whether --enable-sdk was given.
 if test "${enable_sdk+set}" = set; then :
@@ -2965,8 +2971,11 @@ show_explicitly_set "${enable_pb}" "pb machine type"
 show_explicitly_disabled "${enable_pbchunk}" "pbchunk"
 show_explicitly_enabled "${enable_portable}" "portable"
 
-show_explicitly_enabled "${enable_natipkg}" "Adding \"-natipkg\" suffix to library subpath"
-show_explicitly_enabled "${enable_nonatipkg}" "Adding \"-nonatipkg\" suffix to library subpath"
+show_explicitly_enabled "${enable_natipkg}" "Adding \"natipkg\" as shared-object convention and library subpath"
+show_explicitly_enabled "${enable_nonatipkg}" "Adding \"nonatipkg\" as shared-object convention and library subpath"
+if test "${enable_sofind}" != "" ; then
+   echo "=== Setting shared-object convention and library-subpath suffix to ${enable_sofind}"
+fi
 
 show_explicitly_enabled "${enable_libz}" "Installed libz"
 show_explicitly_disabled "${enable_libz}" "Installed libz"
@@ -5189,6 +5198,41 @@ fi
 
 ############## natipkg ################
 
+if test "${enable_natipkg}" = "no" ; then
+  if "${enable_nonatipkg}" = "" ; then
+    if "${enable_sofind}" = "" ; then
+       enable_nonatipkg=yes
+    fi
+  fi
+fi
+
+if test "${enable_nonatipkg}" = "yes" ; then
+  if test "${enable_natipkg}" = "yes" ; then
+     echo 'cannot specify both `--enable-natipkg` and `--enable-nonatipkg`'
+     exit 1
+  fi
+elif test "${enable_nonatipkg}" = "no" ; then
+  if "${enable_nonatipkg}" = "no" ; then
+    if "${enable_sofind}" = "" ; then
+       echo 'cannot specify both `--disable-natipkg` and `--disable-nonatipkg`'
+       echo 'without `--enable-sofind=<sofind>`'
+       exit 1
+    fi
+  fi
+fi
+
+if test "${enable_sofind}" != "" ; then
+  if test "${enable_natipkg}" = "yes" ; then
+     echo 'cannot specify both `--enable-natipkg` and `--enable-sofind`'
+     exit 1
+  fi
+  if test "${enable_nonatipkg}" = "yes" ; then
+     echo 'cannot specify both `--enable-nonatipkg` and `--enable-sofind`'
+     exit 1
+  fi
+fi
+
+
 if test "${enable_natipkg}" = "yes" ; then
   CONFIGURE_RACKET_SO_COMPILE="${CONFIGURE_RACKET_SO_COMPILE} PLT_CS_SLSP_SUFFIX=-natipkg"
   PLT_CS_SLSP_SUFFIX="-natipkg"
@@ -5196,14 +5240,14 @@ if test "${enable_natipkg}" = "yes" ; then
   use_own_zlibs=yes
 fi
 if test "${enable_nonatipkg}" = "yes" ; then
-  if test "${enable_natipkg}" = "yes" ; then
-     echo 'cannot specify both `--enable-natipkg` and `--enable-nonatipkg`'
-     exit 1
-  fi
   CONFIGURE_RACKET_SO_COMPILE="${CONFIGURE_RACKET_SO_COMPILE} PLT_CS_SLSP_SUFFIX=-nonatipkg"
   PLT_CS_SLSP_SUFFIX="-nonatipkg"
   dist_install_missing_pkgs=no
   use_own_zlibs=no
+fi
+if test "${enable_sofind}" != "" ; then
+  CONFIGURE_RACKET_SO_COMPILE="${CONFIGURE_RACKET_SO_COMPILE} PLT_CS_SLSP_SUFFIX=-${enable_sofind}"
+  PLT_CS_SLSP_SUFFIX="-${enable_sofind}"
 fi
 
 ############## ubsan ################
