configure: add `--enable-nonatipkg`
Adding "-nonatipkg" to the end of `system-library-subpath` is intended
for a build environment like MacPorts, where Mac OS libraries are
supplied in the same way as normally supplied on Unix. The extra
suffix will cause platform-specific package dependencies not to match
the usual Mac OS dependencies.

diff --git a/racket/src/bc/configure b/racket/src/bc/configure
--- a/racket/src/bc/configure
+++ b/racket/src/bc/configure
@@ -1517,6 +1517,7 @@ Optional Features:
   --enable-usersetup      setup user-specific files on install
   --enable-portable       prefer portable to host-specific
   --enable-natipkg        add "-natipkg" to library subpath
+  --enable-nonatipkg      add "-nonatipkg" to library subpath
   --enable-shared         create shared libraries (ok, but not recommended)
   --enable-dynlib         same as --enable-shared
   --enable-lt=<prog>      use <prog> instead of libtool; disable to use bundled
@@ -2774,6 +2775,11 @@ if test "${enable_natipkg+set}" = set; then :
   enableval=$enable_natipkg;
 fi
 
+# Check whether --enable-natipkg was given.
+if test "${enable_natipkg+set}" = set; then :
+  enableval=$enable_natipkg;
+fi
+
 
 
 # Check whether --enable-shared was given.
@@ -3417,6 +3423,7 @@ show_explicitly_enabled "${enable_usersetup}" "User-specific setup on install"
 show_explicitly_enabled "${enable_portable}" "portable"
 
 show_explicitly_enabled "${enable_natipkg}" "Adding \"-natipkg\" suffix to library subpath"
+show_explicitly_enabled "${enable_nonatipkg}" "Adding \"-nonatipkg\" suffix to library subpath"
 
 
 show_explicitly_enabled "${enable_xonx}" "Unix style"
@@ -7384,6 +7391,15 @@ fi
 if test "${enable_natipkg}" = "yes" ; then
 
 $as_echo "#define SPLS_SUFFIX \"-natipkg\"" >>confdefs.h
+
+fi
+if test "${enable_nonatipkg}" = "yes" ; then
+  if test "${enable_natipkg}" = "yes" ; then
+     echo 'cannot specify both `--enable-natipkg` and `--enable-nonatipkg`'
+     exit 1
+  fi
+
+$as_echo "#define SPLS_SUFFIX \"-nonatipkg\"" >>confdefs.h
 
 fi
 
diff --git a/racket/src/cs/c/configure b/racket/src/cs/c/configure
--- a/racket/src/cs/c/configure
+++ b/racket/src/cs/c/configure
@@ -1489,6 +1489,7 @@ Optional Features:
   --enable-check          enable extra safety checks for testing
   --enable-portable       prefer portable to host-specific
   --enable-natipkg        add "-natipkg" to library subpath
+  --enable-nonatipkg      add "-nonatipkg" to library subpath
   --enable-sdk=<path>     use Mac OS 10.4 SDK directory
   --enable-sdk5=<path>    use Mac OS 10.5 SDK directory
   --enable-sdk6=<path>    use Mac OS 10.6 SDK directory
@@ -2709,6 +2710,11 @@ if test "${enable_natipkg+set}" = set; then :
   enableval=$enable_natipkg;
 fi
 
+# Check whether --enable-natipkg was given.
+if test "${enable_natipkg+set}" = set; then :
+  enableval=$enable_natipkg;
+fi
+
 
 # Check whether --enable-sdk was given.
 if test "${enable_sdk+set}" = set; then :
@@ -2973,6 +2979,7 @@ show_explicitly_disabled "${enable_pbchunk}" "pbchunk"
 show_explicitly_enabled "${enable_portable}" "portable"
 
 show_explicitly_enabled "${enable_natipkg}" "Adding \"-natipkg\" suffix to library subpath"
+show_explicitly_enabled "${enable_nonatipkg}" "Adding \"-nonatipkg\" suffix to library subpath"
 
 show_explicitly_enabled "${enable_libz}" "Installed libz"
 show_explicitly_disabled "${enable_libz}" "Installed libz"
@@ -5180,6 +5187,14 @@ fi
 if test "${enable_natipkg}" = "yes" ; then
   CONFIGURE_RACKET_SO_COMPILE="${CONFIGURE_RACKET_SO_COMPILE} PLT_CS_SLSP_SUFFIX=-natipkg"
   PLT_CS_SLSP_SUFFIX="-natipkg"
+fi
+if test "${enable_nonatipkg}" = "yes" ; then
+  if test "${enable_natipkg}" = "yes" ; then
+     echo 'cannot specify both `--enable-natipkg` and `--enable-nonatipkg`'
+     exit 1
+  fi
+  CONFIGURE_RACKET_SO_COMPILE="${CONFIGURE_RACKET_SO_COMPILE} PLT_CS_SLSP_SUFFIX=-nonatipkg"
+  PLT_CS_SLSP_SUFFIX="-nonatipkg"
 fi
 
 ############## ubsan ################
