Check that file specified by --enable-racket exists

diff --git a/racket/src/cfg-racket b/racket/src/cfg-racket
--- a/racket/src/cfg-racket
+++ b/racket/src/cfg-racket
@@ -3337,9 +3337,14 @@ fi
 
 if test "${enable_racket}" != "" ; then
   if test "${enable_racket}" = "auto" ; then
-     echo "=== Creating and using local Racket executable"
+    echo "=== Creating and using local Racket executable"
   else
-     echo "=== Using Racket executable ${enable_racket}"
+    if ! test -f "${enable_racket}"; then
+      echo "cannot find racket executable in ${enable_racket}"
+      exit 1
+    else
+      echo "=== Using Racket executable ${enable_racket}"
+    fi
   fi
 fi
 
