upgrade libtool, make xonx and shared work together
svn: r6936

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -1585,8 +1585,11 @@ fi
 
 if test "${enable_shared}" = "yes" ; then
   if test "$OS" = "Darwin" ; then
-    echo "ERROR: don't use --enable-shared or --enable-dynlib under Mac OS X"
-    exit 1
+    if test "${enable_xonx}" != "yes" ; then
+       echo "ERROR: don't use --enable-shared or --enable-dynlib under Mac OS X,"
+       echo "       unless you also use --enable-xonx"
+       exit 1
+    fi
   fi
 fi
 
