better configure reporting when X11 headers/libs missing
svn: r2295

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -5037,16 +5037,6 @@ if test "${enable_dynlib}" = "no" ; then
   enable_shared=no
 fi
 
-if test "${enable_mred}" = "no" ; then
-  enable_wbuild=no
-  enable_xrender=no
-  enable_cairo=no
-  enable_libpng=no
-  enable_libjpeg=no
-  enable_gl=no
-  enable_pthread=no
-fi
-
 enable_quartz=no
 if test "${enable_xonx}" = "yes" ; then
   enable_quartz=no
@@ -5099,6 +5089,16 @@ if test "${enable_mred}" = "yes" ; then
   if test ! -d $srcdir/mred ; then
     enable_mred=no
   fi
+fi
+
+if test "${enable_mred}" = "no" ; then
+  enable_wbuild=no
+  enable_xrender=no
+  enable_cairo=no
+  enable_libpng=no
+  enable_libjpeg=no
+  enable_gl=no
+  enable_pthread=no
 fi
 
 ###### Some defaults #######
@@ -8291,6 +8291,15 @@ fi
 
 fi
 
+   if test "${no_x}" = "yes" ; then
+     echo "***************************************************"
+     echo "configure: cannot find X11 headers and/or libraries,"
+     echo "           which are needed for MrEd"
+     echo "To build just MzScheme, configure with --disable-mred"
+     echo "***************************************************"
+     echo configure aborted
+     exit 1
+   fi
   fi
 
   MAKE_MRED=mr
@@ -12683,5 +12692,4 @@ echo "$as_me: error: $ac_sub_configure failed for $ac_dir" >&2;}
     cd $ac_popdir
   done
 fi
-
 
