detect __sync_bool_compare_and_swap() via `configure'

diff --git a/src/configure b/src/configure
--- a/src/configure
+++ b/src/configure
@@ -8291,6 +8291,77 @@ _ACEOF
   enable_mzrt=yes
 fi
 
+############## compare-and-swap ################
+
+if test "${enable_mzrt}" = "yes" ; then
+   msg="for compare-and-swap"
+  { echo "$as_me:$LINENO: checking $msg" >&5
+echo $ECHO_N "checking $msg... $ECHO_C" >&6; }
+  if test "$cross_compiling" = yes; then
+  cas_available=no
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+int check1(long *addr, long old, long new_val) {
+     return __sync_bool_compare_and_swap(addr, old, new_val);
+   }
+   int check2(short *addr, short old, short new_val) {
+     return __sync_bool_compare_and_swap(addr, old, new_val);
+   }
+   int main() {
+      long l = 2; short s = 3;
+      return !check1(&l, 2, 4) || !check2(&s, 3, 6);
+   }
+_ACEOF
+rm -f conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && { ac_try='./conftest$ac_exeext'
+  { (case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_try") 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  cas_available=yes
+else
+  echo "$as_me: program exited with status $ac_status" >&5
+echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+( exit $ac_status )
+cas_available=no
+fi
+rm -f core *.core core.conftest.* gmon.out bb.out conftest$ac_exeext conftest.$ac_objext conftest.$ac_ext
+fi
+
+
+  { echo "$as_me:$LINENO: result: $cas_available" >&5
+echo "${ECHO_T}$cas_available" >&6; }
+  if test "${cas_available}" = "yes" ; then
+
+cat >>confdefs.h <<\_ACEOF
+#define MZ_CAS_AVAILABLE 1
+_ACEOF
+
+  fi
+fi
+
+
 ############### OS threads ###################
 
 if test "${enable_mzrt}" = "yes" ; then
